# Generated by Django 3.2.22 on 2023-12-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advocate_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=60)),
                ('place', models.CharField(max_length=70)),
                ('post', models.CharField(max_length=70)),
                ('pin', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.IntegerField()),
                ('current_date', models.DateField()),
                ('ADVOCATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=100)),
                ('case_details', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='case_type_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('post', models.FileField(upload_to='')),
                ('pin', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('day', models.DateField()),
                ('Advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('booking_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.booking_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Entry_level_staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='daily_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
            ],
        ),
        migrations.CreateModel(
            name='complains_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complains', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='legel.login_table')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='legel.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='case_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.case')),
            ],
        ),
        migrations.CreateModel(
            name='case_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('CASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.case')),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.user_table'),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='CASE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.case'),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.user_table'),
        ),
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.advocate_table')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.booking_table')),
            ],
        ),
        migrations.AddField(
            model_name='advocate_table',
            name='CASETYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.case_type_table'),
        ),
        migrations.AddField(
            model_name='advocate_table',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legel.login_table'),
        ),
    ]
