# Generated by Django 3.2.22 on 2023-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
