# Generated by Django 3.2.22 on 2024-01-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legel', '0002_alter_booking_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='User',
        ),
    ]
