# Generated by Django 3.2.22 on 2024-01-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legel', '0003_remove_booking_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='legel.user_table'),
            preserve_default=False,
        ),
    ]
