# Generated by Django 3.2.22 on 2024-01-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legel', '0004_enquiry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains_table',
            name='user',
        ),
        migrations.AddField(
            model_name='advocate_table',
            name='idproof',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complains_table',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='legel.login_table'),
            preserve_default=False,
        ),
    ]
