# Generated by Django 3.2.22 on 2024-01-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legel', '0005_auto_20240113_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate_table',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
